import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import AnimatedBackground from '../components/AnimatedBackground';
import { Leaf, ScanLine, MessageCircle, BarChart3, GitCompare, Sparkles, GraduationCap, Users, Navigation, Package } from 'lucide-react';

const features = [
  {
    icon: ScanLine,
    title: 'AI Product Scanner',
    description: "Scan a barcode and get a real sustainability analysis - looked up from OpenFoodFacts' product database and reasoned over by an AI model, not a canned score.",
  },
  {
    icon: MessageCircle,
    title: 'EcoBot Assistant',
    description: 'A chatbot grounded in real sustainability reference material (recycling guidance, material recyclability data) so answers are sourced, not invented - with memory across sessions.',
  },
  {
    icon: BarChart3,
    title: 'Carbon Tracker',
    description: 'Log carbon-emitting activities manually, or describe them in plain language and let AI estimate the footprint using standard emission factors.',
  },
  {
    icon: GitCompare,
    title: 'Product Comparison',
    description: 'Compare products side by side with AI-generated reasoning across packaging, carbon, price, health, and recyclability - grounded in the actual data given, not templated text.',
  },
  {
    icon: Package,
    title: 'Product Lifecycle & Trends',
    description: "A cradle-to-grave breakdown for any product, plus a real trend chart built from your own history of viewing it - never a fabricated curve.",
  },
  {
    icon: Sparkles,
    title: 'Personalized Insights',
    description: 'Recommendations and insights generated from your real scan and carbon-tracking history, not static, one-size-fits-all tips.',
  },
  {
    icon: GraduationCap,
    title: 'Education Center',
    description: 'Real, community-contributed courses, articles, and webinars - anyone can publish one. Complete a course to get a PDF certificate emailed to you, and add webinars straight to your Google Calendar with automatic reminders.',
  },
  {
    icon: Users,
    title: 'Community Hub',
    description: 'Posts, groups with live group chat, events, and challenges - a real, shared space, not a static demo feed.',
  },
  {
    icon: Navigation,
    title: 'Transportation Planner',
    description: 'Real routing across walking, cycling, and driving with genuine distance, time, cost, and emissions for the specific trip you enter.',
  },
];

const About = () => {
  return (
    <div className="relative min-h-screen bg-gradient-to-br from-emerald-50 via-green-50 to-teal-50 dark:from-gray-900 dark:via-gray-800 dark:to-emerald-900 pt-28 pb-16 px-4 overflow-hidden">
      <AnimatedBackground />
      <div className="relative z-10 max-w-4xl mx-auto">
        <div className="text-center mb-12">
          <div className="w-16 h-16 bg-gradient-to-br from-emerald-500 to-green-600 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-lg">
            <Leaf className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-slate-800 dark:text-gray-100 mb-4">About EcoScope</h1>
          <p className="text-lg text-slate-600 dark:text-gray-300 max-w-2xl mx-auto leading-relaxed">
            EcoScope is an AI-powered sustainability app that helps you understand the real environmental
            impact of the products you buy - built around genuine data and real AI reasoning rather than
            static scores.
          </p>
        </div>

        <Card className="mb-10 bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm border-emerald-100 dark:border-emerald-800 rounded-3xl shadow-lg">
          <CardContent className="p-8">
            <h2 className="text-2xl font-bold text-slate-800 dark:text-gray-100 mb-4">Why it exists</h2>
            <p className="text-slate-600 dark:text-gray-300 leading-relaxed mb-4">
              Most "sustainability score" features in shopping apps are static lookups or fabricated numbers
              with no real reasoning behind them. EcoScope takes a different approach: product data comes from
              OpenFoodFacts' real, open database, and the analysis - carbon footprint, packaging, health impact,
              alternatives - is generated by an AI model reasoning over that real data, with every explanation
              traceable back to something concrete rather than invented.
            </p>
            <p className="text-slate-600 dark:text-gray-300 leading-relaxed">
              Where the AI can't ground an answer in real data, it says so explicitly instead of guessing -
              that honesty is a deliberate design choice throughout the app.
            </p>
          </CardContent>
        </Card>

        <h2 className="text-2xl font-bold text-slate-800 dark:text-gray-100 mb-6 text-center">What's inside</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {features.map((feature) => (
            <Card key={feature.title} className="bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm border-emerald-100 dark:border-emerald-800 rounded-2xl shadow-md hover:shadow-lg transition-shadow">
              <CardHeader>
                <CardTitle className="flex items-center space-x-3 text-slate-800 dark:text-gray-100">
                  <div className="w-10 h-10 bg-gradient-to-br from-emerald-500 to-green-600 rounded-xl flex items-center justify-center flex-shrink-0">
                    <feature.icon className="w-5 h-5 text-white" />
                  </div>
                  <span>{feature.title}</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-slate-600 dark:text-gray-300 leading-relaxed">{feature.description}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
};

export default About;
